### ISSUE TITLE
The timeout should cancel the promise and remove it from the stack

### ISSUE THREAD

**Issue by alex-r89** [MrZillaGold/PingMC#82]
Hi there,

Sorry, I'm not 100% if the issue I am facing is down to my implementation or whether its an issue related to this plugin when calling an array of many servers:

I have a situation whereby I map over an array of server IP's and ports, and ping them one by one to get their player count, version etc.  I am noticing however that if one of these servers is offline (or if the IP is not the IP of a minecraft server, for example `notanip:25565`) all subsequent pings will fall into the catch block below.

I believe this may occur because, although I have set the timeout to `3000`, the promise isnt actually canceled and removed from the stack. I may be wrong but I wonder if this is causing subsequent pings to fail when this eventually resolves, which makes online servers fall into the catch block below. 
In my latest test of 10 servers, one being offline caused the subsequent online servers to fall into the catch block and appear offline when they were actually online.

My code example is as follows:

```js
// Servers is an array of minecraft server objects with an IP and port
  for (const server of Servers) {
 let serverPingDetails

    const serverPingDetails =  await new PingMC(`${server.ip}:${server.port}`, 3000)
    .ping()
    .then((data) => {
      serverPingDetails = data
    })
    .catch((error) => {
      console.log(`[ERROR pinging ${server.ip}]`)
      serverPingDetails = null
    })

return serverPingDetails
}
```

This code results in a huge number of servers updating `serverPingDetails` to be `null` because it incorrectly is falling into the catch block.

**Comment by MrZillaGold** [comment]
I apologize for the long answer, I didn't have notifications from the repository enabled. I think this is a problem with your implementation, I wrote a small test and it passes successfully: 

```js
const servers = [
  'pvpland', // Invalid ip
  'prisonfun.co',
  'cavepvp.org',
  'cavepvp.org',
  'mcplayhd.net',
  'onlypvp.pl',
  'lunar.gg',
  'sagepvp.org',
  'dynamicpvp.net',
  'ghostly.live',
  'greev.eu',
  'play.vipermcnet', // Invalid ip
  'introuble.de',
  'minemen.club'
];

(async () => {
  for (const server of servers) {
    await new PingMC(server, 3_000)
        .ping()
        .then(() => console.log("ok"))
        .catch((error) => console.log(error))
  }
})();
```

If possible, send the code that reproduces the problem.

**Comment by MrZillaGold** [comment]
I will close the issue due to inactivity. Feel free to ping me if you have any questions.
